// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package mocks

import (
	models "demomockery/somepkg/models"

	mock "github.com/stretchr/testify/mock"
)

// DataProvider is an autogenerated mock type for the DataProvider type
type DataProvider struct {
	mock.Mock
}

// GetData provides a mock function with given fields: key
func (_m *DataProvider) GetData(key int) ([]models.DataRec, error) {
	ret := _m.Called(key)

	var r0 []models.DataRec
	if rf, ok := ret.Get(0).(func(int) []models.DataRec); ok {
		r0 = rf(key)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.DataRec)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(int) error); ok {
		r1 = rf(key)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
